### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by mcapristo** [mcapristo/taller_de_prog_2_android#26]
- Investigar herramientas
- Definir qué se va a documentar
- Crear subtareas para la documentación

**Comment by urielkusnesov** [comment]
Comenzada la documentacion con sphinx.
Se pusieron los titulos de todo lo que debe estar inlcuido en la documentacion
Parte de la documentacion del proyecto y del manual de usuario realizadas.

**Comment by mcapristo** [comment]
Documentación técnica agregada, acorde al ticket https://github.com/mcapristo/taller_de_prog_2/issues/29
